[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.28.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell", "msi"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = false

[dist.github-custom-runners]
global = "ubuntu-latest"
aarch64-unknown-linux-gnu = "ubuntu-latest"
x86_64-unknown-linux-gnu = "ubuntu-latest"
# x86_64-pc-windows-msvc = "ubuntu-22.04"
# aarch64-apple-darwin = "ubuntu-latest"
# x86_64-apple-darwin = "ubuntu-latest"

[dist.github-custom-runners.x86_64-pc-windows-msvc]
runner = "ubuntu-latest"
host = "x86_64-unknown-linux-gnu"
container = { image = "messense/cargo-xwin", host = "x86_64-unknown-linux-musl", package_manager = "apt" }
